spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imooc-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

  # 关闭session存储
  session:
    store-type: none
#  session:
#    store-type: none
server:
  port: 8060

imooc:
  security:
    browser:
      loginPage: /login.html
      loginType: JSON

#security:
#    basic:
#    enabled: false

endpoints:
  health:
    enabled: false
